// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Azure.MixedReality.ObjectAnchors.Models
{
    /// <summary> Represents an ingestion configuration. </summary>
    public partial class IngestionConfiguration
    {
        public System.Numerics.Vector3? Dimensions { get => DimensionsWrapper.data; set => DimensionsWrapper.data = value; }

        public System.Numerics.Vector3? BoundingBoxCenter { get => BoundingBoxCenterWrapper.data; set => BoundingBoxCenterWrapper.data = value; }

        public System.Numerics.Vector3? Gravity { get => GravityWrapper.data; set => GravityWrapper.data = value; }

        public System.Numerics.Quaternion? PrincipalAxis { get => PrincipalAxisWrapper.data; set => PrincipalAxisWrapper.data = value; }

        /// <summary> Scale of transformation of asset units into meter space. </summary>
        public System.Numerics.Vector4? SupportingPlane { get => SupportingPlaneWrapper.data; set => SupportingPlaneWrapper.data = value; }


        [CodeGenMember("Dimensions")]
        internal Vector3 DimensionsWrapper { get; set; }

        [CodeGenMember("BoundingBoxCenter")]
        internal Vector3 BoundingBoxCenterWrapper { get; set; }

        [CodeGenMember("Gravity")]
        internal Vector3 GravityWrapper { get; set; }

        [CodeGenMember("PrincipalAxis")]
        internal Quaternion PrincipalAxisWrapper { get; set; }

        /// <summary> Scale of transformation of asset units into meter space. </summary>
        [CodeGenMember("SupportingPlane")]
        internal Vector4 SupportingPlaneWrapper { get; set; }
    }
}
