// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Azure.MixedReality.ObjectAnchors.Models
{
    /// <summary> Represents the status of an AOA ingestion job. </summary>
    public partial class IngestionProperties
    {
        /// <summary> The URI for downloading the generated AOA Model. </summary>
        public Uri OutputModelUri
        {
            get
            {
                return new Uri(OutputModelUriString);
            }
        }
        /// <summary> The Uri to the Asset to be ingested by the AOA Ingestion Service. This asset needs to have been uploaded to the service using an endpoint provided from a call to the GetUploadUri API. </summary>
        public Uri InputAssetUri
        {
            get
            {
                return new Uri(InputAssetUriString);
            }
            set
            {
                InputAssetUriString = value.ToString();
            }
        }

        /// <summary> The status of the AOA ingestion job</summary>
        public JobStatus? JobStatus { get; set; }

        [CodeGenMember("OutputModelUri")]
        internal string OutputModelUriString { get; }
        [CodeGenMember("InputAssetUri")]
        internal string InputAssetUriString { get; set; }
    }
}
