// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using Azure.Core;

namespace Azure.MixedReality.ObjectAnchors.Models
{
    /// <summary> The Pose of a trajectory. </summary>
    [CodeGenModel("Pose")]
    public partial class TrajectoryPose
    {
        /// <summary>The pose's rotation</summary>
        public System.Numerics.Quaternion Rotation { get => RotationWrapper.data.HasValue ? RotationWrapper.data.Value : default; set => RotationWrapper.data = value; }
        /// <summary>The pose's translation</summary>
        public System.Numerics.Vector3 Translation { get => TranslationWrapper.data.HasValue ? TranslationWrapper.data.Value : default; set => TranslationWrapper.data = value; }


        [CodeGenMember("Rotation")]
        internal Quaternion RotationWrapper { get; set; }
        [CodeGenMember("Translation")]
        internal Vector3 TranslationWrapper { get; set; }
    }
}
