// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Azure.MixedReality.ObjectAnchors.Models
{
    /// <summary> The Quaternion. </summary>
    public partial class Quaternion
    {
        internal System.Numerics.Quaternion? data = null;

        /// <summary> Initializes a new instance of Quaternion. </summary>
        public Quaternion()
        {
        }

        /// <summary> Initializes a new instance of Quaternion. </summary>
        /// <param name="x"> . </param>
        /// <param name="y"> . </param>
        /// <param name="z"> . </param>
        /// <param name="w"> . </param>
        /// <param name="isIdentity"> . </param>
        internal Quaternion(float? x, float? y, float? z, float? w, bool? isIdentity)
        {
            if (x.HasValue && y.HasValue && z.HasValue && w.HasValue)
            {
                data = new System.Numerics.Quaternion(x.Value, y.Value, z.Value, z.Value);
            }
        }

        public float? X
        {
            get
            {
                return data.HasValue ? data.Value.X : null;
            }
            set
            {
                if (value == null)
                {
                    data = null;
                }
                if (data.HasValue)
                {
                    var tmp = data.Value;
                    tmp.X = value.Value;
                    data = tmp;
                }
                else
                {
                    var tmp = new System.Numerics.Quaternion();
                    tmp.X = value.Value;
                    data = tmp;
                }
            }
        }

        public float? Y
        {
            get
            {
                return data.HasValue ? data.Value.Y : null;
            }
            set
            {
                if (value == null)
                {
                    data = null;
                }
                if (data.HasValue)
                {
                    var tmp = data.Value;
                    tmp.Y = value.Value;
                    data = tmp;
                }
                else
                {
                    var tmp = new System.Numerics.Quaternion();
                    tmp.Y = value.Value;
                    data = tmp;
                }
            }
        }

        public float? Z
        {
            get
            {
                return data.HasValue ? data.Value.Z : null;
            }
            set
            {
                if (value == null)
                {
                    data = null;
                }
                if (data.HasValue)
                {
                    var tmp = data.Value;
                    tmp.Z = value.Value;
                    data = tmp;
                }
                else
                {
                    var tmp = new System.Numerics.Quaternion();
                    tmp.Z = value.Value;
                    data = tmp;
                }
            }
        }

        public float? W
        {
            get
            {
                return data.HasValue ? data.Value.W : null;
            }
            set
            {
                if (value == null)
                {
                    data = null;
                }
                if (data.HasValue)
                {
                    var tmp = data.Value;
                    tmp.W = value.Value;
                    data = tmp;
                }
                else
                {
                    var tmp = new System.Numerics.Quaternion();
                    tmp.W = value.Value;
                    data = tmp;
                }
            }
        }

        public bool? IsIdentity { get => data.HasValue ? data.Value.IsIdentity : null; }
    }
}
