// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Azure.MixedReality.ObjectAnchors.Models
{
    /// <summary> The UploadLocation. </summary>
    internal partial class UploadLocation
    {
    }
}
