// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Azure.MixedReality.ObjectAnchors.Models
{
    /// <summary> The Vector4. </summary>
    internal partial class Vector4
    {
        internal System.Numerics.Vector4? data = null;

        /// <summary> Initializes a new instance of Vector4. </summary>
        internal Vector4()
        {
        }

        internal Vector4(System.Numerics.Vector4 vector)
        {
            data = vector;
        }

        /// <summary> Initializes a new instance of Vector4. </summary>
        /// <param name="x"> . </param>
        /// <param name="y"> . </param>
        /// <param name="z"> . </param>
        /// <param name="w"> . </param>
        internal Vector4(float? x, float? y, float? z, float? w)
        {
            if (x.HasValue && y.HasValue && z.HasValue && w.HasValue)
            {
                data = new System.Numerics.Vector4(x.Value, y.Value, z.Value, z.Value);
            }
        }

        public float? X
        {
            get
            {
                return data.HasValue ? data.Value.X : null;
            }
            set
            {
                if (value == null)
                {
                    data = null;
                }
                if (data.HasValue)
                {
                    var tmp = data.Value;
                    tmp.X = value.Value;
                    data = tmp;
                }
                else
                {
                    var tmp = new System.Numerics.Vector4();
                    tmp.X = value.Value;
                    data = tmp;
                }
            }
        }

        public float? Y
        {
            get
            {
                return data.HasValue ? data.Value.Y : null;
            }
            set
            {
                if (value == null)
                {
                    data = null;
                }
                if (data.HasValue)
                {
                    var tmp = data.Value;
                    tmp.Y = value.Value;
                    data = tmp;
                }
                else
                {
                    var tmp = new System.Numerics.Vector4();
                    tmp.Y = value.Value;
                    data = tmp;
                }
            }
        }

        public float? Z
        {
            get
            {
                return data.HasValue ? data.Value.Z : null;
            }
            set
            {
                if (value == null)
                {
                    data = null;
                }
                if (data.HasValue)
                {
                    var tmp = data.Value;
                    tmp.Z = value.Value;
                    data = tmp;
                }
                else
                {
                    var tmp = new System.Numerics.Vector4();
                    tmp.Z = value.Value;
                    data = tmp;
                }
            }
        }

        public float? W
        {
            get
            {
                return data.HasValue ? data.Value.W : null;
            }
            set
            {
                if (value == null)
                {
                    data = null;
                }
                if (data.HasValue)
                {
                    var tmp = data.Value;
                    tmp.W = value.Value;
                    data = tmp;
                }
                else
                {
                    var tmp = new System.Numerics.Vector4();
                    tmp.W = value.Value;
                    data = tmp;
                }
            }
        }
    }
}
