// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Microsoft">
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------
namespace Azure.MixedReality.ObjectAnchors
{
    using Microsoft.Azure.MixedReality.Sts;
    using System;
    using System.IO;
    using System.Numerics;

    /// <summary>
    /// Represents an Object Anchors ingestion job request.
    /// </summary>
    public class IngestionJobRequest
    {
        /// <summary>
        /// Gets the asset configuration values.
        /// </summary>
        public AssetConfiguration AssetConfigurationValues { get; }

        /// <summary>
        /// The file type of the asset.
        /// </summary>
        public string AssetFileType { get; }

        /// <summary>
        /// The path to the Asset to be ingested by the Object Anchors service.
        /// </summary>
        public string InputFilePath { get; }

        /// <summary>
        /// The path to save the the model generated by the Object Anchors service.
        /// </summary>
        public string OutputFilePath { get; }

        /// <summary>
        /// Identifier for the Object Anchors Ingestion ServiceResponse.
        /// </summary>
        public Guid JobId { get; } = Guid.NewGuid();

        /// <summary>
        /// Initializes a new instance of the <see cref="IngestionJobRequest"/> class.
        /// </summary>
        /// <param name="assetGravity">The asset gravity.</param>
        /// <param name="assetScale">The asset scale.</param>
        /// <param name="inputFilePath">The path to the Asset to be ingested by the Object Anchors service.</param>
        /// <param name="outputFilePath">The path to save the the model generated by the Object Anchors service.</param>
        public IngestionJobRequest(Vector3 assetGravity, float assetScale, string inputFilePath, string outputFilePath = null)
            : this(new AssetConfiguration(assetGravity, assetScale), inputFilePath, outputFilePath)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IngestionJobRequest"/> class.
        /// </summary>
        /// <param name="assetGravity">The asset gravity.</param>
        /// <param name="unit">The unit of measurement.</param>
        /// <param name="inputFilePath">The path to the Asset to be ingested by the Object Anchors service.</param>
        /// <param name="outputFilePath">The path to save the the model generated by the Object Anchors service.</param>
        public IngestionJobRequest(Vector3 assetGravity, Unit unit, string inputFilePath, string outputFilePath = null)
            : this(new AssetConfiguration(assetGravity, AssetScaleGenerator.GetAssetScale(unit)), inputFilePath, outputFilePath)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IngestionJobRequest"/> class.
        /// </summary>
        /// <param name="assetConfiguration">The asset configuration.</param>
        /// <param name="inputFilePath">The path to the Asset to be ingested by the Object Anchors service.</param>
        /// <param name="outputFilePath">The path to save the model generated by the Object Anchors service.</param>
        public IngestionJobRequest(AssetConfiguration assetConfiguration, string inputFilePath, string outputFilePath = null)
        {
            if (string.IsNullOrWhiteSpace(inputFilePath))
            {
                throw new ArgumentNullOrWhiteSpaceException(nameof(inputFilePath));
            }

            if (string.IsNullOrWhiteSpace(outputFilePath))
            {
                outputFilePath = $"{Path.GetDirectoryName(inputFilePath)}\\{Path.GetFileNameWithoutExtension(inputFilePath)}_{this.JobId}.ou";
            }

            if (assetConfiguration is null)
            {
                throw new ArgumentNullException(nameof(assetConfiguration));
            }

            if (!assetConfiguration.IsValid(out string assetConfigurationInvalidMessage))
            {
                throw new ArgumentException(assetConfigurationInvalidMessage, nameof(assetConfiguration));
            }

            this.InputFilePath = inputFilePath;
            this.AssetFileType = Path.GetExtension(inputFilePath);
            this.AssetConfigurationValues = assetConfiguration;
            this.OutputFilePath = outputFilePath;
        }
    }
}
