// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Azure.MixedReality.ObjectAnchors.Models
{
    /// <summary> Represents an ingestion configuration. </summary>
    public partial class IngestionConfiguration
    {
        [CodeGenMember("Dimensions")]
        internal Vector3 GeneratedDimensions { get; set; }

        [CodeGenMember("BoundingBoxCenter")]
        internal Vector3 GeneratedBoundingBoxCenter { get; set; }

        [CodeGenMember("Gravity")]
        internal Vector3 GeneratedGravity { get; set; }
        /// <summary> Indices of Key Frames. </summary>
        public IList<int> KeyFrameIndexes { get; }
        /// <summary> Ground truth trajectory. </summary>
        public IList<Pose> GtTrajectory { get; }
        [CodeGenMember("PrincipalAxis")]
        internal Quaternion GeneratedPrincipalAxis { get; set; }
        /// <summary> Scale of transformation of asset units into meter space. </summary>
        public float Scale { get; set; }
        [CodeGenMember("SupportingPlane")]
        internal Vector4 GeneratedSupportingPlane { get; set; }
        /// <summary> Test Trajectory. </summary>
        public IList<Pose> TestTrajectory { get; }
    }
}
