# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
    - master
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/spatialanchors/

pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/spatialanchors/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: template
    ArtifactName: packages
    Artifacts:
    - name: Azure.MixedReality.SpatialAnchors
      safeName: AzureMixedRealitySpatialAnchors
